databases:
  - name: budget-tracker-db
    plan: free
    databaseName: budgetdb
    user: budgetuser

services:
  - type: web
    name: budget-tracker-web
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /accounts/login/
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: budget-tracker-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: budget-tracker-redis
          type: keyvalue
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: budget-tracker-redis
          type: keyvalue
          property: connectionString

  - type: worker
    name: budget-tracker-worker
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: celery -A budgetproject worker -l info
    envVars:
      - key: RUN_MIGRATIONS
        value: "false"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: budget-tracker-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: budget-tracker-redis
          type: keyvalue
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: budget-tracker-redis
          type: keyvalue
          property: connectionString

  - type: worker
    name: budget-tracker-beat
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: celery -A budgetproject beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    envVars:
      - key: RUN_MIGRATIONS
        value: "false"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: budget-tracker-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: budget-tracker-redis
          type: keyvalue
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: budget-tracker-redis
          type: keyvalue
          property: connectionString

  - type: keyvalue
    name: budget-tracker-redis
    plan: free
    ipAllowList: []
